/* automatically generated by rust-bindgen */

#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]
pub const __llvm__: ::std::os::raw::c_uchar = 1;
pub const __clang__: ::std::os::raw::c_uchar = 1;
pub const __clang_major__: ::std::os::raw::c_uchar = 7;
pub const __clang_minor__: ::std::os::raw::c_uchar = 3;
pub const __clang_patchlevel__: ::std::os::raw::c_uchar = 0;
pub const __GNUC_MINOR__: ::std::os::raw::c_uchar = 2;
pub const __GNUC_PATCHLEVEL__: ::std::os::raw::c_uchar = 1;
pub const __GNUC__: ::std::os::raw::c_uchar = 4;
pub const __GXX_ABI_VERSION: ::std::os::raw::c_ushort = 1002;
pub const __ATOMIC_RELAXED: ::std::os::raw::c_uchar = 0;
pub const __ATOMIC_CONSUME: ::std::os::raw::c_uchar = 1;
pub const __ATOMIC_ACQUIRE: ::std::os::raw::c_uchar = 2;
pub const __ATOMIC_RELEASE: ::std::os::raw::c_uchar = 3;
pub const __ATOMIC_ACQ_REL: ::std::os::raw::c_uchar = 4;
pub const __ATOMIC_SEQ_CST: ::std::os::raw::c_uchar = 5;
pub const __PRAGMA_REDEFINE_EXTNAME: ::std::os::raw::c_uchar = 1;
pub const __CONSTANT_CFSTRINGS__: ::std::os::raw::c_uchar = 1;
pub const __BLOCKS__: ::std::os::raw::c_uchar = 1;
pub const __GXX_RTTI: ::std::os::raw::c_uchar = 1;
pub const __ORDER_LITTLE_ENDIAN__: ::std::os::raw::c_ushort = 1234;
pub const __ORDER_BIG_ENDIAN__: ::std::os::raw::c_ushort = 4321;
pub const __ORDER_PDP_ENDIAN__: ::std::os::raw::c_ushort = 3412;
pub const __BYTE_ORDER__: ::std::os::raw::c_ushort = 1234;
pub const __LITTLE_ENDIAN__: ::std::os::raw::c_uchar = 1;
pub const _LP64: ::std::os::raw::c_uchar = 1;
pub const __LP64__: ::std::os::raw::c_uchar = 1;
pub const __CHAR_BIT__: ::std::os::raw::c_uchar = 8;
pub const __SCHAR_MAX__: ::std::os::raw::c_uchar = 127;
pub const __SHRT_MAX__: ::std::os::raw::c_ushort = 32767;
pub const __INT_MAX__: ::std::os::raw::c_uint = 2147483647;
pub const __LONG_MAX__: ::std::os::raw::c_ulonglong = 9223372036854775807;
pub const __LONG_LONG_MAX__: ::std::os::raw::c_ulonglong =
    9223372036854775807;
pub const __WCHAR_MAX__: ::std::os::raw::c_uint = 2147483647;
pub const __INTMAX_MAX__: ::std::os::raw::c_ulonglong = 9223372036854775807;
pub const __SIZE_MAX__: ::std::os::raw::c_char = -1;
pub const __UINTMAX_MAX__: ::std::os::raw::c_char = -1;
pub const __PTRDIFF_MAX__: ::std::os::raw::c_ulonglong = 9223372036854775807;
pub const __INTPTR_MAX__: ::std::os::raw::c_ulonglong = 9223372036854775807;
pub const __UINTPTR_MAX__: ::std::os::raw::c_char = -1;
pub const __SIZEOF_DOUBLE__: ::std::os::raw::c_uchar = 8;
pub const __SIZEOF_FLOAT__: ::std::os::raw::c_uchar = 4;
pub const __SIZEOF_INT__: ::std::os::raw::c_uchar = 4;
pub const __SIZEOF_LONG__: ::std::os::raw::c_uchar = 8;
pub const __SIZEOF_LONG_DOUBLE__: ::std::os::raw::c_uchar = 16;
pub const __SIZEOF_LONG_LONG__: ::std::os::raw::c_uchar = 8;
pub const __SIZEOF_POINTER__: ::std::os::raw::c_uchar = 8;
pub const __SIZEOF_SHORT__: ::std::os::raw::c_uchar = 2;
pub const __SIZEOF_PTRDIFF_T__: ::std::os::raw::c_uchar = 8;
pub const __SIZEOF_SIZE_T__: ::std::os::raw::c_uchar = 8;
pub const __SIZEOF_WCHAR_T__: ::std::os::raw::c_uchar = 4;
pub const __SIZEOF_WINT_T__: ::std::os::raw::c_uchar = 4;
pub const __SIZEOF_INT128__: ::std::os::raw::c_uchar = 16;
pub const __INTMAX_WIDTH__: ::std::os::raw::c_uchar = 64;
pub const __PTRDIFF_WIDTH__: ::std::os::raw::c_uchar = 64;
pub const __INTPTR_WIDTH__: ::std::os::raw::c_uchar = 64;
pub const __SIZE_WIDTH__: ::std::os::raw::c_uchar = 64;
pub const __WCHAR_WIDTH__: ::std::os::raw::c_uchar = 32;
pub const __WINT_WIDTH__: ::std::os::raw::c_uchar = 32;
pub const __SIG_ATOMIC_WIDTH__: ::std::os::raw::c_uchar = 32;
pub const __SIG_ATOMIC_MAX__: ::std::os::raw::c_uint = 2147483647;
pub const __UINTMAX_WIDTH__: ::std::os::raw::c_uchar = 64;
pub const __UINTPTR_WIDTH__: ::std::os::raw::c_uchar = 64;
pub const __FLT_HAS_DENORM__: ::std::os::raw::c_uchar = 1;
pub const __FLT_DIG__: ::std::os::raw::c_uchar = 6;
pub const __FLT_DECIMAL_DIG__: ::std::os::raw::c_uchar = 9;
pub const __FLT_HAS_INFINITY__: ::std::os::raw::c_uchar = 1;
pub const __FLT_HAS_QUIET_NAN__: ::std::os::raw::c_uchar = 1;
pub const __FLT_MANT_DIG__: ::std::os::raw::c_uchar = 24;
pub const __FLT_MAX_10_EXP__: ::std::os::raw::c_uchar = 38;
pub const __FLT_MAX_EXP__: ::std::os::raw::c_uchar = 128;
pub const __FLT_MIN_10_EXP__: ::std::os::raw::c_char = -37;
pub const __FLT_MIN_EXP__: ::std::os::raw::c_char = -125;
pub const __DBL_HAS_DENORM__: ::std::os::raw::c_uchar = 1;
pub const __DBL_DIG__: ::std::os::raw::c_uchar = 15;
pub const __DBL_DECIMAL_DIG__: ::std::os::raw::c_uchar = 17;
pub const __DBL_HAS_INFINITY__: ::std::os::raw::c_uchar = 1;
pub const __DBL_HAS_QUIET_NAN__: ::std::os::raw::c_uchar = 1;
pub const __DBL_MANT_DIG__: ::std::os::raw::c_uchar = 53;
pub const __DBL_MAX_10_EXP__: ::std::os::raw::c_ushort = 308;
pub const __DBL_MAX_EXP__: ::std::os::raw::c_ushort = 1024;
pub const __DBL_MIN_10_EXP__: ::std::os::raw::c_short = -307;
pub const __DBL_MIN_EXP__: ::std::os::raw::c_short = -1021;
pub const __LDBL_HAS_DENORM__: ::std::os::raw::c_uchar = 1;
pub const __LDBL_DIG__: ::std::os::raw::c_uchar = 18;
pub const __LDBL_DECIMAL_DIG__: ::std::os::raw::c_uchar = 21;
pub const __LDBL_HAS_INFINITY__: ::std::os::raw::c_uchar = 1;
pub const __LDBL_HAS_QUIET_NAN__: ::std::os::raw::c_uchar = 1;
pub const __LDBL_MANT_DIG__: ::std::os::raw::c_uchar = 64;
pub const __LDBL_MAX_10_EXP__: ::std::os::raw::c_ushort = 4932;
pub const __LDBL_MAX_EXP__: ::std::os::raw::c_ushort = 16384;
pub const __LDBL_MIN_10_EXP__: ::std::os::raw::c_short = -4931;
pub const __LDBL_MIN_EXP__: ::std::os::raw::c_short = -16381;
pub const __POINTER_WIDTH__: ::std::os::raw::c_uchar = 64;
pub const __BIGGEST_ALIGNMENT__: ::std::os::raw::c_uchar = 16;
pub const __UINT8_MAX__: ::std::os::raw::c_uchar = 255;
pub const __INT8_MAX__: ::std::os::raw::c_uchar = 127;
pub const __UINT16_MAX__: ::std::os::raw::c_ushort = 65535;
pub const __INT16_MAX__: ::std::os::raw::c_ushort = 32767;
pub const __UINT32_MAX__: ::std::os::raw::c_uint = 4294967295;
pub const __INT32_MAX__: ::std::os::raw::c_uint = 2147483647;
pub const __UINT64_MAX__: ::std::os::raw::c_char = -1;
pub const __INT64_MAX__: ::std::os::raw::c_ulonglong = 9223372036854775807;
pub const __INT_LEAST8_MAX__: ::std::os::raw::c_uchar = 127;
pub const __UINT_LEAST8_MAX__: ::std::os::raw::c_uchar = 255;
pub const __INT_LEAST16_MAX__: ::std::os::raw::c_ushort = 32767;
pub const __UINT_LEAST16_MAX__: ::std::os::raw::c_ushort = 65535;
pub const __INT_LEAST32_MAX__: ::std::os::raw::c_uint = 2147483647;
pub const __UINT_LEAST32_MAX__: ::std::os::raw::c_uint = 4294967295;
pub const __INT_LEAST64_MAX__: ::std::os::raw::c_ulonglong =
    9223372036854775807;
pub const __UINT_LEAST64_MAX__: ::std::os::raw::c_char = -1;
pub const __INT_FAST8_MAX__: ::std::os::raw::c_uchar = 127;
pub const __UINT_FAST8_MAX__: ::std::os::raw::c_uchar = 255;
pub const __INT_FAST16_MAX__: ::std::os::raw::c_ushort = 32767;
pub const __UINT_FAST16_MAX__: ::std::os::raw::c_ushort = 65535;
pub const __INT_FAST32_MAX__: ::std::os::raw::c_uint = 2147483647;
pub const __UINT_FAST32_MAX__: ::std::os::raw::c_uint = 4294967295;
pub const __INT_FAST64_MAX__: ::std::os::raw::c_ulonglong =
    9223372036854775807;
pub const __UINT_FAST64_MAX__: ::std::os::raw::c_char = -1;
pub const __FINITE_MATH_ONLY__: ::std::os::raw::c_uchar = 0;
pub const __GNUC_STDC_INLINE__: ::std::os::raw::c_uchar = 1;
pub const __GCC_ATOMIC_TEST_AND_SET_TRUEVAL: ::std::os::raw::c_uchar = 1;
pub const __GCC_ATOMIC_BOOL_LOCK_FREE: ::std::os::raw::c_uchar = 2;
pub const __GCC_ATOMIC_CHAR_LOCK_FREE: ::std::os::raw::c_uchar = 2;
pub const __GCC_ATOMIC_CHAR16_T_LOCK_FREE: ::std::os::raw::c_uchar = 2;
pub const __GCC_ATOMIC_CHAR32_T_LOCK_FREE: ::std::os::raw::c_uchar = 2;
pub const __GCC_ATOMIC_WCHAR_T_LOCK_FREE: ::std::os::raw::c_uchar = 2;
pub const __GCC_ATOMIC_SHORT_LOCK_FREE: ::std::os::raw::c_uchar = 2;
pub const __GCC_ATOMIC_INT_LOCK_FREE: ::std::os::raw::c_uchar = 2;
pub const __GCC_ATOMIC_LONG_LOCK_FREE: ::std::os::raw::c_uchar = 2;
pub const __GCC_ATOMIC_LLONG_LOCK_FREE: ::std::os::raw::c_uchar = 2;
pub const __GCC_ATOMIC_POINTER_LOCK_FREE: ::std::os::raw::c_uchar = 2;
pub const __NO_INLINE__: ::std::os::raw::c_uchar = 1;
pub const __PIC__: ::std::os::raw::c_uchar = 2;
pub const __pic__: ::std::os::raw::c_uchar = 2;
pub const __FLT_EVAL_METHOD__: ::std::os::raw::c_uchar = 0;
pub const __FLT_RADIX__: ::std::os::raw::c_uchar = 2;
pub const __DECIMAL_DIG__: ::std::os::raw::c_uchar = 21;
pub const __SSP__: ::std::os::raw::c_uchar = 1;
pub const __amd64__: ::std::os::raw::c_uchar = 1;
pub const __amd64: ::std::os::raw::c_uchar = 1;
pub const __x86_64: ::std::os::raw::c_uchar = 1;
pub const __x86_64__: ::std::os::raw::c_uchar = 1;
pub const __core2: ::std::os::raw::c_uchar = 1;
pub const __core2__: ::std::os::raw::c_uchar = 1;
pub const __tune_core2__: ::std::os::raw::c_uchar = 1;
pub const __NO_MATH_INLINES: ::std::os::raw::c_uchar = 1;
pub const __FXSR__: ::std::os::raw::c_uchar = 1;
pub const __GCC_HAVE_SYNC_COMPARE_AND_SWAP_16: ::std::os::raw::c_uchar = 1;
pub const __SSSE3__: ::std::os::raw::c_uchar = 1;
pub const __SSE3__: ::std::os::raw::c_uchar = 1;
pub const __SSE2__: ::std::os::raw::c_uchar = 1;
pub const __SSE2_MATH__: ::std::os::raw::c_uchar = 1;
pub const __SSE__: ::std::os::raw::c_uchar = 1;
pub const __SSE_MATH__: ::std::os::raw::c_uchar = 1;
pub const __MMX__: ::std::os::raw::c_uchar = 1;
pub const __GCC_HAVE_SYNC_COMPARE_AND_SWAP_1: ::std::os::raw::c_uchar = 1;
pub const __GCC_HAVE_SYNC_COMPARE_AND_SWAP_2: ::std::os::raw::c_uchar = 1;
pub const __GCC_HAVE_SYNC_COMPARE_AND_SWAP_4: ::std::os::raw::c_uchar = 1;
pub const __GCC_HAVE_SYNC_COMPARE_AND_SWAP_8: ::std::os::raw::c_uchar = 1;
pub const __APPLE_CC__: ::std::os::raw::c_ushort = 6000;
pub const __APPLE__: ::std::os::raw::c_uchar = 1;
pub const OBJC_NEW_PROPERTIES: ::std::os::raw::c_uchar = 1;
pub const __apple_build_version__: ::std::os::raw::c_uint = 7030031;
pub const __DYNAMIC__: ::std::os::raw::c_uchar = 1;
pub const __ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__:
          ::std::os::raw::c_uint =
    101100;
pub const __MACH__: ::std::os::raw::c_uchar = 1;
pub const __STDC__: ::std::os::raw::c_uchar = 1;
pub const __STDC_HOSTED__: ::std::os::raw::c_uchar = 1;
pub const __STDC_VERSION__: ::std::os::raw::c_uint = 201112;
pub const __STDC_UTF_16__: ::std::os::raw::c_uchar = 1;
pub const __STDC_UTF_32__: ::std::os::raw::c_uchar = 1;
pub const __DARWIN_ONLY_64_BIT_INO_T: ::std::os::raw::c_uchar = 0;
pub const __DARWIN_ONLY_VERS_1050: ::std::os::raw::c_uchar = 0;
pub const __DARWIN_ONLY_UNIX_CONFORMANCE: ::std::os::raw::c_uchar = 1;
pub const __DARWIN_UNIX03: ::std::os::raw::c_uchar = 1;
pub const __DARWIN_64_BIT_INO_T: ::std::os::raw::c_uchar = 1;
pub const __DARWIN_VERS_1050: ::std::os::raw::c_uchar = 1;
pub const __DARWIN_NON_CANCELABLE: ::std::os::raw::c_uchar = 0;
pub const __DARWIN_C_ANSI: ::std::os::raw::c_ushort = 4096;
pub const __DARWIN_C_FULL: ::std::os::raw::c_uint = 900000;
pub const __DARWIN_C_LEVEL: ::std::os::raw::c_uint = 900000;
pub const __STDC_WANT_LIB_EXT1__: ::std::os::raw::c_uchar = 1;
pub const _DARWIN_FEATURE_64_BIT_INODE: ::std::os::raw::c_uchar = 1;
pub const _DARWIN_FEATURE_ONLY_UNIX_CONFORMANCE: ::std::os::raw::c_uchar = 1;
pub const _DARWIN_FEATURE_UNIX_CONFORMANCE: ::std::os::raw::c_uchar = 3;
pub const __MAC_10_0: ::std::os::raw::c_ushort = 1000;
pub const __MAC_10_1: ::std::os::raw::c_ushort = 1010;
pub const __MAC_10_2: ::std::os::raw::c_ushort = 1020;
pub const __MAC_10_3: ::std::os::raw::c_ushort = 1030;
pub const __MAC_10_4: ::std::os::raw::c_ushort = 1040;
pub const __MAC_10_5: ::std::os::raw::c_ushort = 1050;
pub const __MAC_10_6: ::std::os::raw::c_ushort = 1060;
pub const __MAC_10_7: ::std::os::raw::c_ushort = 1070;
pub const __MAC_10_8: ::std::os::raw::c_ushort = 1080;
pub const __MAC_10_9: ::std::os::raw::c_ushort = 1090;
pub const __MAC_10_10: ::std::os::raw::c_uint = 101000;
pub const __MAC_10_10_2: ::std::os::raw::c_uint = 101002;
pub const __MAC_10_10_3: ::std::os::raw::c_uint = 101003;
pub const __MAC_10_11: ::std::os::raw::c_uint = 101100;
pub const __MAC_10_11_2: ::std::os::raw::c_uint = 101102;
pub const __MAC_10_11_3: ::std::os::raw::c_uint = 101103;
pub const __MAC_10_11_4: ::std::os::raw::c_uint = 101104;
pub const __IPHONE_2_0: ::std::os::raw::c_ushort = 20000;
pub const __IPHONE_2_1: ::std::os::raw::c_ushort = 20100;
pub const __IPHONE_2_2: ::std::os::raw::c_ushort = 20200;
pub const __IPHONE_3_0: ::std::os::raw::c_ushort = 30000;
pub const __IPHONE_3_1: ::std::os::raw::c_ushort = 30100;
pub const __IPHONE_3_2: ::std::os::raw::c_ushort = 30200;
pub const __IPHONE_4_0: ::std::os::raw::c_ushort = 40000;
pub const __IPHONE_4_1: ::std::os::raw::c_ushort = 40100;
pub const __IPHONE_4_2: ::std::os::raw::c_ushort = 40200;
pub const __IPHONE_4_3: ::std::os::raw::c_ushort = 40300;
pub const __IPHONE_5_0: ::std::os::raw::c_ushort = 50000;
pub const __IPHONE_5_1: ::std::os::raw::c_ushort = 50100;
pub const __IPHONE_6_0: ::std::os::raw::c_ushort = 60000;
pub const __IPHONE_6_1: ::std::os::raw::c_ushort = 60100;
pub const __IPHONE_7_0: ::std::os::raw::c_uint = 70000;
pub const __IPHONE_7_1: ::std::os::raw::c_uint = 70100;
pub const __IPHONE_8_0: ::std::os::raw::c_uint = 80000;
pub const __IPHONE_8_1: ::std::os::raw::c_uint = 80100;
pub const __IPHONE_8_2: ::std::os::raw::c_uint = 80200;
pub const __IPHONE_8_3: ::std::os::raw::c_uint = 80300;
pub const __IPHONE_8_4: ::std::os::raw::c_uint = 80400;
pub const __IPHONE_9_0: ::std::os::raw::c_uint = 90000;
pub const __IPHONE_9_1: ::std::os::raw::c_uint = 90100;
pub const __IPHONE_9_2: ::std::os::raw::c_uint = 90200;
pub const __IPHONE_9_3: ::std::os::raw::c_uint = 90300;
pub const __TVOS_9_0: ::std::os::raw::c_uint = 90000;
pub const __TVOS_9_1: ::std::os::raw::c_uint = 90100;
pub const __TVOS_9_2: ::std::os::raw::c_uint = 90200;
pub const __WATCHOS_1_0: ::std::os::raw::c_ushort = 10000;
pub const __WATCHOS_2_0: ::std::os::raw::c_ushort = 20000;
pub const __MAC_OS_X_VERSION_MIN_REQUIRED: ::std::os::raw::c_uint = 101100;
pub const __MAC_OS_X_VERSION_MAX_ALLOWED: ::std::os::raw::c_uint = 101104;
pub const __PTHREAD_SIZE__: ::std::os::raw::c_ushort = 8176;
pub const __PTHREAD_ATTR_SIZE__: ::std::os::raw::c_uchar = 56;
pub const __PTHREAD_MUTEXATTR_SIZE__: ::std::os::raw::c_uchar = 8;
pub const __PTHREAD_MUTEX_SIZE__: ::std::os::raw::c_uchar = 56;
pub const __PTHREAD_CONDATTR_SIZE__: ::std::os::raw::c_uchar = 8;
pub const __PTHREAD_COND_SIZE__: ::std::os::raw::c_uchar = 40;
pub const __PTHREAD_ONCE_SIZE__: ::std::os::raw::c_uchar = 8;
pub const __PTHREAD_RWLOCK_SIZE__: ::std::os::raw::c_uchar = 192;
pub const __PTHREAD_RWLOCKATTR_SIZE__: ::std::os::raw::c_uchar = 16;
pub const __DARWIN_WCHAR_MAX: ::std::os::raw::c_uint = 2147483647;
pub const __DARWIN_WCHAR_MIN: ::std::os::raw::c_int = -2147483648;
pub const _FORTIFY_SOURCE: ::std::os::raw::c_uchar = 2;
pub const __SLBF: ::std::os::raw::c_uchar = 1;
pub const __SNBF: ::std::os::raw::c_uchar = 2;
pub const __SRD: ::std::os::raw::c_uchar = 4;
pub const __SWR: ::std::os::raw::c_uchar = 8;
pub const __SRW: ::std::os::raw::c_uchar = 16;
pub const __SEOF: ::std::os::raw::c_uchar = 32;
pub const __SERR: ::std::os::raw::c_uchar = 64;
pub const __SMBF: ::std::os::raw::c_uchar = 128;
pub const __SAPP: ::std::os::raw::c_ushort = 256;
pub const __SSTR: ::std::os::raw::c_ushort = 512;
pub const __SOPT: ::std::os::raw::c_ushort = 1024;
pub const __SNPT: ::std::os::raw::c_ushort = 2048;
pub const __SOFF: ::std::os::raw::c_ushort = 4096;
pub const __SMOD: ::std::os::raw::c_ushort = 8192;
pub const __SALC: ::std::os::raw::c_ushort = 16384;
pub const __SIGN: ::std::os::raw::c_ushort = 32768;
pub const _IOFBF: ::std::os::raw::c_uchar = 0;
pub const _IOLBF: ::std::os::raw::c_uchar = 1;
pub const _IONBF: ::std::os::raw::c_uchar = 2;
pub const BUFSIZ: ::std::os::raw::c_ushort = 1024;
pub const EOF: ::std::os::raw::c_char = -1;
pub const FOPEN_MAX: ::std::os::raw::c_uchar = 20;
pub const FILENAME_MAX: ::std::os::raw::c_ushort = 1024;
pub const L_tmpnam: ::std::os::raw::c_ushort = 1024;
pub const TMP_MAX: ::std::os::raw::c_uint = 308915776;
pub const SEEK_SET: ::std::os::raw::c_uchar = 0;
pub const SEEK_CUR: ::std::os::raw::c_uchar = 1;
pub const SEEK_END: ::std::os::raw::c_uchar = 2;
pub const L_ctermid: ::std::os::raw::c_ushort = 1024;
pub const __CTERMID_DEFINED: ::std::os::raw::c_uchar = 1;
pub const _USE_FORTIFY_LEVEL: ::std::os::raw::c_uchar = 2;
pub const __WORDSIZE: ::std::os::raw::c_uchar = 64;
pub const INT8_MAX: ::std::os::raw::c_uchar = 127;
pub const INT16_MAX: ::std::os::raw::c_ushort = 32767;
pub const INT32_MAX: ::std::os::raw::c_uint = 2147483647;
pub const INT64_MAX: ::std::os::raw::c_ulonglong = 9223372036854775807;
pub const INT8_MIN: ::std::os::raw::c_char = -128;
pub const INT16_MIN: ::std::os::raw::c_short = -32768;
pub const INT32_MIN: ::std::os::raw::c_int = -2147483648;
pub const INT64_MIN: ::std::os::raw::c_longlong = -9223372036854775808;
pub const UINT8_MAX: ::std::os::raw::c_uchar = 255;
pub const UINT16_MAX: ::std::os::raw::c_ushort = 65535;
pub const UINT32_MAX: ::std::os::raw::c_uint = 4294967295;
pub const UINT64_MAX: ::std::os::raw::c_char = -1;
pub const INT_LEAST8_MIN: ::std::os::raw::c_char = -128;
pub const INT_LEAST16_MIN: ::std::os::raw::c_short = -32768;
pub const INT_LEAST32_MIN: ::std::os::raw::c_int = -2147483648;
pub const INT_LEAST64_MIN: ::std::os::raw::c_longlong = -9223372036854775808;
pub const INT_LEAST8_MAX: ::std::os::raw::c_uchar = 127;
pub const INT_LEAST16_MAX: ::std::os::raw::c_ushort = 32767;
pub const INT_LEAST32_MAX: ::std::os::raw::c_uint = 2147483647;
pub const INT_LEAST64_MAX: ::std::os::raw::c_ulonglong = 9223372036854775807;
pub const UINT_LEAST8_MAX: ::std::os::raw::c_uchar = 255;
pub const UINT_LEAST16_MAX: ::std::os::raw::c_ushort = 65535;
pub const UINT_LEAST32_MAX: ::std::os::raw::c_uint = 4294967295;
pub const UINT_LEAST64_MAX: ::std::os::raw::c_char = -1;
pub const INT_FAST8_MIN: ::std::os::raw::c_char = -128;
pub const INT_FAST16_MIN: ::std::os::raw::c_short = -32768;
pub const INT_FAST32_MIN: ::std::os::raw::c_int = -2147483648;
pub const INT_FAST64_MIN: ::std::os::raw::c_longlong = -9223372036854775808;
pub const INT_FAST8_MAX: ::std::os::raw::c_uchar = 127;
pub const INT_FAST16_MAX: ::std::os::raw::c_ushort = 32767;
pub const INT_FAST32_MAX: ::std::os::raw::c_uint = 2147483647;
pub const INT_FAST64_MAX: ::std::os::raw::c_ulonglong = 9223372036854775807;
pub const UINT_FAST8_MAX: ::std::os::raw::c_uchar = 255;
pub const UINT_FAST16_MAX: ::std::os::raw::c_ushort = 65535;
pub const UINT_FAST32_MAX: ::std::os::raw::c_uint = 4294967295;
pub const UINT_FAST64_MAX: ::std::os::raw::c_char = -1;
pub const INTPTR_MIN: ::std::os::raw::c_longlong = -9223372036854775808;
pub const INTPTR_MAX: ::std::os::raw::c_ulonglong = 9223372036854775807;
pub const UINTPTR_MAX: ::std::os::raw::c_char = -1;
pub const INTMAX_MIN: ::std::os::raw::c_longlong = -9223372036854775808;
pub const INTMAX_MAX: ::std::os::raw::c_ulonglong = 9223372036854775807;
pub const UINTMAX_MAX: ::std::os::raw::c_char = -1;
pub const PTRDIFF_MIN: ::std::os::raw::c_longlong = -9223372036854775808;
pub const PTRDIFF_MAX: ::std::os::raw::c_ulonglong = 9223372036854775807;
pub const SIZE_MAX: ::std::os::raw::c_char = -1;
pub const RSIZE_MAX: ::std::os::raw::c_char = -1;
pub const WCHAR_MAX: ::std::os::raw::c_uint = 2147483647;
pub const WCHAR_MIN: ::std::os::raw::c_int = -2147483648;
pub const WINT_MIN: ::std::os::raw::c_int = -2147483648;
pub const WINT_MAX: ::std::os::raw::c_uint = 2147483647;
pub const SIG_ATOMIC_MIN: ::std::os::raw::c_int = -2147483648;
pub const SIG_ATOMIC_MAX: ::std::os::raw::c_uint = 2147483647;
pub const _QUAD_HIGHWORD: ::std::os::raw::c_uchar = 1;
pub const _QUAD_LOWWORD: ::std::os::raw::c_uchar = 0;
pub const __DARWIN_LITTLE_ENDIAN: ::std::os::raw::c_ushort = 1234;
pub const __DARWIN_BIG_ENDIAN: ::std::os::raw::c_ushort = 4321;
pub const __DARWIN_PDP_ENDIAN: ::std::os::raw::c_ushort = 3412;
pub const __DARWIN_BYTE_ORDER: ::std::os::raw::c_ushort = 1234;
pub const LITTLE_ENDIAN: ::std::os::raw::c_ushort = 1234;
pub const BIG_ENDIAN: ::std::os::raw::c_ushort = 4321;
pub const PDP_ENDIAN: ::std::os::raw::c_ushort = 3412;
pub const BYTE_ORDER: ::std::os::raw::c_ushort = 1234;
pub const __DARWIN_FD_SETSIZE: ::std::os::raw::c_ushort = 1024;
pub const __DARWIN_NBBY: ::std::os::raw::c_uchar = 8;
pub const NBBY: ::std::os::raw::c_uchar = 8;
pub const FD_SETSIZE: ::std::os::raw::c_ushort = 1024;
pub const RD_KAFKA_VERSION: ::std::os::raw::c_uint = 590591;
pub const RD_KAFKA_OFFSET_BEGINNING: ::std::os::raw::c_char = -2;
pub const RD_KAFKA_OFFSET_END: ::std::os::raw::c_char = -1;
pub const RD_KAFKA_OFFSET_STORED: ::std::os::raw::c_short = -1000;
pub const RD_KAFKA_OFFSET_INVALID: ::std::os::raw::c_short = -1001;
pub const RD_KAFKA_OFFSET_TAIL_BASE: ::std::os::raw::c_short = -2000;
pub const RD_KAFKA_MSG_F_FREE: ::std::os::raw::c_uchar = 1;
pub const RD_KAFKA_MSG_F_COPY: ::std::os::raw::c_uchar = 2;
pub const RD_KAFKA_MSG_F_BLOCK: ::std::os::raw::c_uchar = 4;
pub const RD_KAFKA_EVENT_NONE: ::std::os::raw::c_uchar = 0;
pub const RD_KAFKA_EVENT_DR: ::std::os::raw::c_uchar = 1;
pub const RD_KAFKA_EVENT_FETCH: ::std::os::raw::c_uchar = 2;
pub const RD_KAFKA_EVENT_LOG: ::std::os::raw::c_uchar = 4;
pub const RD_KAFKA_EVENT_ERROR: ::std::os::raw::c_uchar = 8;
pub const RD_KAFKA_EVENT_REBALANCE: ::std::os::raw::c_uchar = 16;
pub const RD_KAFKA_EVENT_OFFSET_COMMIT: ::std::os::raw::c_uchar = 32;
pub type __int8_t = ::std::os::raw::c_char;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int16_t = ::std::os::raw::c_short;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __int64_t = ::std::os::raw::c_longlong;
pub type __uint64_t = ::std::os::raw::c_ulonglong;
pub type __darwin_intptr_t = ::std::os::raw::c_long;
pub type __darwin_natural_t = ::std::os::raw::c_uint;
pub type __darwin_ct_rune_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Copy)]
pub struct __mbstate_t {
    pub _bindgen_data_: [u64; 16usize],
}
impl __mbstate_t {
    pub unsafe fn __mbstate8(&mut self)
     -> *mut [::std::os::raw::c_char; 128usize] {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn _mbstateL(&mut self) -> *mut ::std::os::raw::c_longlong {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
}
impl ::std::clone::Clone for __mbstate_t {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for __mbstate_t {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type __darwin_mbstate_t = __mbstate_t;
pub type __darwin_ptrdiff_t = ::std::os::raw::c_long;
pub type __darwin_size_t = ::std::os::raw::c_ulong;
pub type __darwin_va_list = __builtin_va_list;
pub type __darwin_wchar_t = ::std::os::raw::c_int;
pub type __darwin_rune_t = __darwin_wchar_t;
pub type __darwin_wint_t = ::std::os::raw::c_int;
pub type __darwin_clock_t = ::std::os::raw::c_ulong;
pub type __darwin_socklen_t = __uint32_t;
pub type __darwin_ssize_t = ::std::os::raw::c_long;
pub type __darwin_time_t = ::std::os::raw::c_long;
pub type __darwin_blkcnt_t = __int64_t;
pub type __darwin_blksize_t = __int32_t;
pub type __darwin_dev_t = __int32_t;
pub type __darwin_fsblkcnt_t = ::std::os::raw::c_uint;
pub type __darwin_fsfilcnt_t = ::std::os::raw::c_uint;
pub type __darwin_gid_t = __uint32_t;
pub type __darwin_id_t = __uint32_t;
pub type __darwin_ino64_t = __uint64_t;
pub type __darwin_ino_t = __darwin_ino64_t;
pub type __darwin_mach_port_name_t = __darwin_natural_t;
pub type __darwin_mach_port_t = __darwin_mach_port_name_t;
pub type __darwin_mode_t = __uint16_t;
pub type __darwin_off_t = __int64_t;
pub type __darwin_pid_t = __int32_t;
pub type __darwin_sigset_t = __uint32_t;
pub type __darwin_suseconds_t = __int32_t;
pub type __darwin_uid_t = __uint32_t;
pub type __darwin_useconds_t = __uint32_t;
pub type __darwin_uuid_t = [::std::os::raw::c_uchar; 16usize];
pub type __darwin_uuid_string_t = [::std::os::raw::c_char; 37usize];
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct __darwin_pthread_handler_rec {
    pub __routine: ::std::option::Option<unsafe extern "C" fn(arg1:
                                                                  *mut ::std::os::raw::c_void)>,
    pub __arg: *mut ::std::os::raw::c_void,
    pub __next: *mut __darwin_pthread_handler_rec,
}
impl ::std::default::Default for __darwin_pthread_handler_rec {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy)]
pub struct _opaque_pthread_attr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 56usize],
}
impl ::std::clone::Clone for _opaque_pthread_attr_t {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for _opaque_pthread_attr_t {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy)]
pub struct _opaque_pthread_cond_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 40usize],
}
impl ::std::clone::Clone for _opaque_pthread_cond_t {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for _opaque_pthread_cond_t {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct _opaque_pthread_condattr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 8usize],
}
impl ::std::default::Default for _opaque_pthread_condattr_t {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy)]
pub struct _opaque_pthread_mutex_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 56usize],
}
impl ::std::clone::Clone for _opaque_pthread_mutex_t {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for _opaque_pthread_mutex_t {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct _opaque_pthread_mutexattr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 8usize],
}
impl ::std::default::Default for _opaque_pthread_mutexattr_t {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct _opaque_pthread_once_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 8usize],
}
impl ::std::default::Default for _opaque_pthread_once_t {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy)]
pub struct _opaque_pthread_rwlock_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 192usize],
}
impl ::std::clone::Clone for _opaque_pthread_rwlock_t {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for _opaque_pthread_rwlock_t {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct _opaque_pthread_rwlockattr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 16usize],
}
impl ::std::default::Default for _opaque_pthread_rwlockattr_t {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy)]
pub struct _opaque_pthread_t {
    pub __sig: ::std::os::raw::c_long,
    pub __cleanup_stack: *mut __darwin_pthread_handler_rec,
    pub __opaque: [::std::os::raw::c_char; 8176usize],
}
impl ::std::clone::Clone for _opaque_pthread_t {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for _opaque_pthread_t {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type __darwin_pthread_attr_t = _opaque_pthread_attr_t;
pub type __darwin_pthread_cond_t = _opaque_pthread_cond_t;
pub type __darwin_pthread_condattr_t = _opaque_pthread_condattr_t;
pub type __darwin_pthread_key_t = ::std::os::raw::c_ulong;
pub type __darwin_pthread_mutex_t = _opaque_pthread_mutex_t;
pub type __darwin_pthread_mutexattr_t = _opaque_pthread_mutexattr_t;
pub type __darwin_pthread_once_t = _opaque_pthread_once_t;
pub type __darwin_pthread_rwlock_t = _opaque_pthread_rwlock_t;
pub type __darwin_pthread_rwlockattr_t = _opaque_pthread_rwlockattr_t;
pub type __darwin_pthread_t = *mut _opaque_pthread_t;
pub type __darwin_nl_item = ::std::os::raw::c_int;
pub type __darwin_wctrans_t = ::std::os::raw::c_int;
pub type __darwin_wctype_t = __uint32_t;
pub type va_list = __darwin_va_list;
pub type size_t = usize;
pub type fpos_t = __darwin_off_t;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct __sbuf {
    pub _base: *mut ::std::os::raw::c_uchar,
    pub _size: ::std::os::raw::c_int,
}
impl ::std::default::Default for __sbuf {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub enum __sFILEX { }
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct __sFILE {
    pub _p: *mut ::std::os::raw::c_uchar,
    pub _r: ::std::os::raw::c_int,
    pub _w: ::std::os::raw::c_int,
    pub _flags: ::std::os::raw::c_short,
    pub _file: ::std::os::raw::c_short,
    pub _bf: __sbuf,
    pub _lbfsize: ::std::os::raw::c_int,
    pub _cookie: *mut ::std::os::raw::c_void,
    pub _close: ::std::option::Option<unsafe extern "C" fn(arg1:
                                                               *mut ::std::os::raw::c_void)
                                          -> ::std::os::raw::c_int>,
    pub _read: ::std::option::Option<unsafe extern "C" fn(arg1:
                                                              *mut ::std::os::raw::c_void,
                                                          arg2:
                                                              *mut ::std::os::raw::c_char,
                                                          arg3:
                                                              ::std::os::raw::c_int)
                                         -> ::std::os::raw::c_int>,
    pub _seek: ::std::option::Option<unsafe extern "C" fn(arg1:
                                                              *mut ::std::os::raw::c_void,
                                                          arg2: fpos_t,
                                                          arg3:
                                                              ::std::os::raw::c_int)
                                         -> fpos_t>,
    pub _write: ::std::option::Option<unsafe extern "C" fn(arg1:
                                                               *mut ::std::os::raw::c_void,
                                                           arg2:
                                                               *const ::std::os::raw::c_char,
                                                           arg3:
                                                               ::std::os::raw::c_int)
                                          -> ::std::os::raw::c_int>,
    pub _ub: __sbuf,
    pub _extra: *mut __sFILEX,
    pub _ur: ::std::os::raw::c_int,
    pub _ubuf: [::std::os::raw::c_uchar; 3usize],
    pub _nbuf: [::std::os::raw::c_uchar; 1usize],
    pub _lb: __sbuf,
    pub _blksize: ::std::os::raw::c_int,
    pub _offset: fpos_t,
}
impl ::std::default::Default for __sFILE {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type FILE = __sFILE;
pub type off_t = __darwin_off_t;
pub type ssize_t = isize;
pub type wchar_t = __darwin_wchar_t;
pub type int8_t = i8;
pub type int16_t = i16;
pub type int32_t = i32;
pub type int64_t = i64;
pub type uint8_t = u8;
pub type uint16_t = u16;
pub type uint32_t = u32;
pub type uint64_t = u64;
pub type int_least8_t = int8_t;
pub type int_least16_t = int16_t;
pub type int_least32_t = int32_t;
pub type int_least64_t = int64_t;
pub type uint_least8_t = uint8_t;
pub type uint_least16_t = uint16_t;
pub type uint_least32_t = uint32_t;
pub type uint_least64_t = uint64_t;
pub type int_fast8_t = int8_t;
pub type int_fast16_t = int16_t;
pub type int_fast32_t = int32_t;
pub type int_fast64_t = int64_t;
pub type uint_fast8_t = uint8_t;
pub type uint_fast16_t = uint16_t;
pub type uint_fast32_t = uint32_t;
pub type uint_fast64_t = uint64_t;
pub type intptr_t = isize;
pub type uintptr_t = usize;
pub type intmax_t = ::std::os::raw::c_long;
pub type uintmax_t = ::std::os::raw::c_ulong;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct imaxdiv_t {
    pub quot: intmax_t,
    pub rem: intmax_t,
}
impl ::std::default::Default for imaxdiv_t {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type u_int8_t = ::std::os::raw::c_uchar;
pub type u_int16_t = ::std::os::raw::c_ushort;
pub type u_int32_t = ::std::os::raw::c_uint;
pub type u_int64_t = ::std::os::raw::c_ulonglong;
pub type register_t = int64_t;
pub type user_addr_t = u_int64_t;
pub type user_size_t = u_int64_t;
pub type user_ssize_t = int64_t;
pub type user_long_t = int64_t;
pub type user_ulong_t = u_int64_t;
pub type user_time_t = int64_t;
pub type user_off_t = int64_t;
pub type syscall_arg_t = u_int64_t;
pub type u_char = ::std::os::raw::c_uchar;
pub type u_short = ::std::os::raw::c_ushort;
pub type u_int = ::std::os::raw::c_uint;
pub type u_long = ::std::os::raw::c_ulong;
pub type ushort = ::std::os::raw::c_ushort;
pub type uint_ = ::std::os::raw::c_uint;
pub type u_quad_t = u_int64_t;
pub type quad_t = int64_t;
pub type qaddr_t = *mut quad_t;
pub type caddr_t = *mut ::std::os::raw::c_char;
pub type daddr_t = int32_t;
pub type dev_t = __darwin_dev_t;
pub type fixpt_t = u_int32_t;
pub type blkcnt_t = __darwin_blkcnt_t;
pub type blksize_t = __darwin_blksize_t;
pub type gid_t = __darwin_gid_t;
pub type in_addr_t = __uint32_t;
pub type in_port_t = __uint16_t;
pub type ino_t = __darwin_ino_t;
pub type ino64_t = __darwin_ino64_t;
pub type key_t = __int32_t;
pub type mode_t = __darwin_mode_t;
pub type nlink_t = __uint16_t;
pub type id_t = __darwin_id_t;
pub type pid_t = __darwin_pid_t;
pub type segsz_t = int32_t;
pub type swblk_t = int32_t;
pub type uid_t = __darwin_uid_t;
pub type clock_t = __darwin_clock_t;
pub type time_t = __darwin_time_t;
pub type useconds_t = __darwin_useconds_t;
pub type suseconds_t = __darwin_suseconds_t;
pub type rsize_t = __darwin_size_t;
pub type errno_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct fd_set {
    pub fds_bits: [__int32_t; 32usize],
}
impl ::std::default::Default for fd_set {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type fd_mask = __int32_t;
pub type pthread_attr_t = __darwin_pthread_attr_t;
pub type pthread_cond_t = __darwin_pthread_cond_t;
pub type pthread_condattr_t = __darwin_pthread_condattr_t;
pub type pthread_mutex_t = __darwin_pthread_mutex_t;
pub type pthread_mutexattr_t = __darwin_pthread_mutexattr_t;
pub type pthread_once_t = __darwin_pthread_once_t;
pub type pthread_rwlock_t = __darwin_pthread_rwlock_t;
pub type pthread_rwlockattr_t = __darwin_pthread_rwlockattr_t;
pub type pthread_t = __darwin_pthread_t;
pub type pthread_key_t = __darwin_pthread_key_t;
pub type fsblkcnt_t = __darwin_fsblkcnt_t;
pub type fsfilcnt_t = __darwin_fsfilcnt_t;
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum rd_kafka_type_t { RD_KAFKA_PRODUCER = 0, RD_KAFKA_CONSUMER = 1, }
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum rd_kafka_timestamp_type_t {
    RD_KAFKA_TIMESTAMP_NOT_AVAILABLE = 0,
    RD_KAFKA_TIMESTAMP_CREATE_TIME = 1,
    RD_KAFKA_TIMESTAMP_LOG_APPEND_TIME = 2,
}
pub enum rd_kafka_s { }
pub type rd_kafka_t = rd_kafka_s;
pub enum rd_kafka_topic_s { }
pub type rd_kafka_topic_t = rd_kafka_topic_s;
pub enum rd_kafka_conf_s { }
pub type rd_kafka_conf_t = rd_kafka_conf_s;
pub enum rd_kafka_topic_conf_s { }
pub type rd_kafka_topic_conf_t = rd_kafka_topic_conf_s;
pub enum rd_kafka_queue_s { }
pub type rd_kafka_queue_t = rd_kafka_queue_s;
#[derive(Copy, Clone)]
#[repr(i32)]
#[derive(Debug)]
pub enum rd_kafka_resp_err_t {
    RD_KAFKA_RESP_ERR__BEGIN = -200,
    RD_KAFKA_RESP_ERR__BAD_MSG = -199,
    RD_KAFKA_RESP_ERR__BAD_COMPRESSION = -198,
    RD_KAFKA_RESP_ERR__DESTROY = -197,
    RD_KAFKA_RESP_ERR__FAIL = -196,
    RD_KAFKA_RESP_ERR__TRANSPORT = -195,
    RD_KAFKA_RESP_ERR__CRIT_SYS_RESOURCE = -194,
    RD_KAFKA_RESP_ERR__RESOLVE = -193,
    RD_KAFKA_RESP_ERR__MSG_TIMED_OUT = -192,
    RD_KAFKA_RESP_ERR__PARTITION_EOF = -191,
    RD_KAFKA_RESP_ERR__UNKNOWN_PARTITION = -190,
    RD_KAFKA_RESP_ERR__FS = -189,
    RD_KAFKA_RESP_ERR__UNKNOWN_TOPIC = -188,
    RD_KAFKA_RESP_ERR__ALL_BROKERS_DOWN = -187,
    RD_KAFKA_RESP_ERR__INVALID_ARG = -186,
    RD_KAFKA_RESP_ERR__TIMED_OUT = -185,
    RD_KAFKA_RESP_ERR__QUEUE_FULL = -184,
    RD_KAFKA_RESP_ERR__ISR_INSUFF = -183,
    RD_KAFKA_RESP_ERR__NODE_UPDATE = -182,
    RD_KAFKA_RESP_ERR__SSL = -181,
    RD_KAFKA_RESP_ERR__WAIT_COORD = -180,
    RD_KAFKA_RESP_ERR__UNKNOWN_GROUP = -179,
    RD_KAFKA_RESP_ERR__IN_PROGRESS = -178,
    RD_KAFKA_RESP_ERR__PREV_IN_PROGRESS = -177,
    RD_KAFKA_RESP_ERR__EXISTING_SUBSCRIPTION = -176,
    RD_KAFKA_RESP_ERR__ASSIGN_PARTITIONS = -175,
    RD_KAFKA_RESP_ERR__REVOKE_PARTITIONS = -174,
    RD_KAFKA_RESP_ERR__CONFLICT = -173,
    RD_KAFKA_RESP_ERR__STATE = -172,
    RD_KAFKA_RESP_ERR__UNKNOWN_PROTOCOL = -171,
    RD_KAFKA_RESP_ERR__NOT_IMPLEMENTED = -170,
    RD_KAFKA_RESP_ERR__AUTHENTICATION = -169,
    RD_KAFKA_RESP_ERR__NO_OFFSET = -168,
    RD_KAFKA_RESP_ERR__OUTDATED = -167,
    RD_KAFKA_RESP_ERR__TIMED_OUT_QUEUE = -166,
    RD_KAFKA_RESP_ERR__END = -100,
    RD_KAFKA_RESP_ERR_UNKNOWN = -1,
    RD_KAFKA_RESP_ERR_NO_ERROR = 0,
    RD_KAFKA_RESP_ERR_OFFSET_OUT_OF_RANGE = 1,
    RD_KAFKA_RESP_ERR_INVALID_MSG = 2,
    RD_KAFKA_RESP_ERR_UNKNOWN_TOPIC_OR_PART = 3,
    RD_KAFKA_RESP_ERR_INVALID_MSG_SIZE = 4,
    RD_KAFKA_RESP_ERR_LEADER_NOT_AVAILABLE = 5,
    RD_KAFKA_RESP_ERR_NOT_LEADER_FOR_PARTITION = 6,
    RD_KAFKA_RESP_ERR_REQUEST_TIMED_OUT = 7,
    RD_KAFKA_RESP_ERR_BROKER_NOT_AVAILABLE = 8,
    RD_KAFKA_RESP_ERR_REPLICA_NOT_AVAILABLE = 9,
    RD_KAFKA_RESP_ERR_MSG_SIZE_TOO_LARGE = 10,
    RD_KAFKA_RESP_ERR_STALE_CTRL_EPOCH = 11,
    RD_KAFKA_RESP_ERR_OFFSET_METADATA_TOO_LARGE = 12,
    RD_KAFKA_RESP_ERR_NETWORK_EXCEPTION = 13,
    RD_KAFKA_RESP_ERR_GROUP_LOAD_IN_PROGRESS = 14,
    RD_KAFKA_RESP_ERR_GROUP_COORDINATOR_NOT_AVAILABLE = 15,
    RD_KAFKA_RESP_ERR_NOT_COORDINATOR_FOR_GROUP = 16,
    RD_KAFKA_RESP_ERR_TOPIC_EXCEPTION = 17,
    RD_KAFKA_RESP_ERR_RECORD_LIST_TOO_LARGE = 18,
    RD_KAFKA_RESP_ERR_NOT_ENOUGH_REPLICAS = 19,
    RD_KAFKA_RESP_ERR_NOT_ENOUGH_REPLICAS_AFTER_APPEND = 20,
    RD_KAFKA_RESP_ERR_INVALID_REQUIRED_ACKS = 21,
    RD_KAFKA_RESP_ERR_ILLEGAL_GENERATION = 22,
    RD_KAFKA_RESP_ERR_INCONSISTENT_GROUP_PROTOCOL = 23,
    RD_KAFKA_RESP_ERR_INVALID_GROUP_ID = 24,
    RD_KAFKA_RESP_ERR_UNKNOWN_MEMBER_ID = 25,
    RD_KAFKA_RESP_ERR_INVALID_SESSION_TIMEOUT = 26,
    RD_KAFKA_RESP_ERR_REBALANCE_IN_PROGRESS = 27,
    RD_KAFKA_RESP_ERR_INVALID_COMMIT_OFFSET_SIZE = 28,
    RD_KAFKA_RESP_ERR_TOPIC_AUTHORIZATION_FAILED = 29,
    RD_KAFKA_RESP_ERR_GROUP_AUTHORIZATION_FAILED = 30,
    RD_KAFKA_RESP_ERR_CLUSTER_AUTHORIZATION_FAILED = 31,
    RD_KAFKA_RESP_ERR_INVALID_TIMESTAMP = 32,
    RD_KAFKA_RESP_ERR_UNSUPPORTED_SASL_MECHANISM = 33,
    RD_KAFKA_RESP_ERR_ILLEGAL_SASL_STATE = 34,
    RD_KAFKA_RESP_ERR_UNSUPPORTED_VERSION = 35,
    RD_KAFKA_RESP_ERR_END_ALL = 36,
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct rd_kafka_err_desc {
    pub code: rd_kafka_resp_err_t,
    pub name: *const ::std::os::raw::c_char,
    pub desc: *const ::std::os::raw::c_char,
}
impl ::std::default::Default for rd_kafka_err_desc {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct rd_kafka_topic_partition_s {
    pub topic: *mut ::std::os::raw::c_char,
    pub partition: int32_t,
    pub offset: int64_t,
    pub metadata: *mut ::std::os::raw::c_void,
    pub metadata_size: size_t,
    pub opaque: *mut ::std::os::raw::c_void,
    pub err: rd_kafka_resp_err_t,
    pub _private: *mut ::std::os::raw::c_void,
}
impl ::std::default::Default for rd_kafka_topic_partition_s {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type rd_kafka_topic_partition_t = rd_kafka_topic_partition_s;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct rd_kafka_topic_partition_list_s {
    pub cnt: ::std::os::raw::c_int,
    pub size: ::std::os::raw::c_int,
    pub elems: *mut rd_kafka_topic_partition_t,
}
impl ::std::default::Default for rd_kafka_topic_partition_list_s {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type rd_kafka_topic_partition_list_t = rd_kafka_topic_partition_list_s;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct rd_kafka_message_s {
    pub err: rd_kafka_resp_err_t,
    pub rkt: *mut rd_kafka_topic_t,
    pub partition: int32_t,
    pub payload: *mut ::std::os::raw::c_void,
    pub len: size_t,
    pub key: *mut ::std::os::raw::c_void,
    pub key_len: size_t,
    pub offset: int64_t,
    pub _private: *mut ::std::os::raw::c_void,
}
impl ::std::default::Default for rd_kafka_message_s {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type rd_kafka_message_t = rd_kafka_message_s;
#[derive(Copy, Clone)]
#[repr(i32)]
#[derive(Debug)]
pub enum rd_kafka_conf_res_t {
    RD_KAFKA_CONF_UNKNOWN = -2,
    RD_KAFKA_CONF_INVALID = -1,
    RD_KAFKA_CONF_OK = 0,
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct rd_kafka_metadata_broker {
    pub id: int32_t,
    pub host: *mut ::std::os::raw::c_char,
    pub port: ::std::os::raw::c_int,
}
impl ::std::default::Default for rd_kafka_metadata_broker {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type rd_kafka_metadata_broker_t = rd_kafka_metadata_broker;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct rd_kafka_metadata_partition {
    pub id: int32_t,
    pub err: rd_kafka_resp_err_t,
    pub leader: int32_t,
    pub replica_cnt: ::std::os::raw::c_int,
    pub replicas: *mut int32_t,
    pub isr_cnt: ::std::os::raw::c_int,
    pub isrs: *mut int32_t,
}
impl ::std::default::Default for rd_kafka_metadata_partition {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type rd_kafka_metadata_partition_t = rd_kafka_metadata_partition;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct rd_kafka_metadata_topic {
    pub topic: *mut ::std::os::raw::c_char,
    pub partition_cnt: ::std::os::raw::c_int,
    pub partitions: *mut rd_kafka_metadata_partition,
    pub err: rd_kafka_resp_err_t,
}
impl ::std::default::Default for rd_kafka_metadata_topic {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type rd_kafka_metadata_topic_t = rd_kafka_metadata_topic;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct rd_kafka_metadata {
    pub broker_cnt: ::std::os::raw::c_int,
    pub brokers: *mut rd_kafka_metadata_broker,
    pub topic_cnt: ::std::os::raw::c_int,
    pub topics: *mut rd_kafka_metadata_topic,
    pub orig_broker_id: int32_t,
    pub orig_broker_name: *mut ::std::os::raw::c_char,
}
impl ::std::default::Default for rd_kafka_metadata {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type rd_kafka_metadata_t = rd_kafka_metadata;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct rd_kafka_group_member_info {
    pub member_id: *mut ::std::os::raw::c_char,
    pub client_id: *mut ::std::os::raw::c_char,
    pub client_host: *mut ::std::os::raw::c_char,
    pub member_metadata: *mut ::std::os::raw::c_void,
    pub member_metadata_size: ::std::os::raw::c_int,
    pub member_assignment: *mut ::std::os::raw::c_void,
    pub member_assignment_size: ::std::os::raw::c_int,
}
impl ::std::default::Default for rd_kafka_group_member_info {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct rd_kafka_group_info {
    pub broker: rd_kafka_metadata_broker,
    pub group: *mut ::std::os::raw::c_char,
    pub err: rd_kafka_resp_err_t,
    pub state: *mut ::std::os::raw::c_char,
    pub protocol_type: *mut ::std::os::raw::c_char,
    pub protocol: *mut ::std::os::raw::c_char,
    pub members: *mut rd_kafka_group_member_info,
    pub member_cnt: ::std::os::raw::c_int,
}
impl ::std::default::Default for rd_kafka_group_info {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct rd_kafka_group_list {
    pub groups: *mut rd_kafka_group_info,
    pub group_cnt: ::std::os::raw::c_int,
}
impl ::std::default::Default for rd_kafka_group_list {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type rd_kafka_event_type_t = ::std::os::raw::c_int;
pub enum rd_kafka_op_s { }
pub type rd_kafka_event_t = rd_kafka_op_s;
pub type __builtin_va_list = [__va_list_tag; 1usize];
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct __va_list_tag {
    pub gp_offset: ::std::os::raw::c_uint,
    pub fp_offset: ::std::os::raw::c_uint,
    pub overflow_arg_area: *mut ::std::os::raw::c_void,
    pub reg_save_area: *mut ::std::os::raw::c_void,
}
impl ::std::default::Default for __va_list_tag {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
extern "C" {
    pub static mut __stdinp: *mut FILE;
    pub static mut __stdoutp: *mut FILE;
    pub static mut __stderrp: *mut FILE;
    pub static sys_nerr: ::std::os::raw::c_int;
    pub static mut sys_errlist: [*const ::std::os::raw::c_char; 0usize];
}
extern "C" {
    pub fn renameat(arg1: ::std::os::raw::c_int,
                    arg2: *const ::std::os::raw::c_char,
                    arg3: ::std::os::raw::c_int,
                    arg4: *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn clearerr(arg1: *mut FILE);
    pub fn fclose(arg1: *mut FILE) -> ::std::os::raw::c_int;
    pub fn feof(arg1: *mut FILE) -> ::std::os::raw::c_int;
    pub fn ferror(arg1: *mut FILE) -> ::std::os::raw::c_int;
    pub fn fflush(arg1: *mut FILE) -> ::std::os::raw::c_int;
    pub fn fgetc(arg1: *mut FILE) -> ::std::os::raw::c_int;
    pub fn fgetpos(arg1: *mut FILE, arg2: *mut fpos_t)
     -> ::std::os::raw::c_int;
    pub fn fgets(arg1: *mut ::std::os::raw::c_char,
                 arg2: ::std::os::raw::c_int, arg3: *mut FILE)
     -> *mut ::std::os::raw::c_char;
    pub fn fopen(arg1: *const ::std::os::raw::c_char,
                 arg2: *const ::std::os::raw::c_char) -> *mut FILE;
    pub fn fprintf(arg1: *mut FILE, arg2: *const ::std::os::raw::c_char, ...)
     -> ::std::os::raw::c_int;
    pub fn fputc(arg1: ::std::os::raw::c_int, arg2: *mut FILE)
     -> ::std::os::raw::c_int;
    pub fn fputs(arg1: *const ::std::os::raw::c_char, arg2: *mut FILE)
     -> ::std::os::raw::c_int;
    pub fn fread(arg1: *mut ::std::os::raw::c_void, arg2: size_t,
                 arg3: size_t, arg4: *mut FILE) -> size_t;
    pub fn freopen(arg1: *const ::std::os::raw::c_char,
                   arg2: *const ::std::os::raw::c_char, arg3: *mut FILE)
     -> *mut FILE;
    pub fn fscanf(arg1: *mut FILE, arg2: *const ::std::os::raw::c_char, ...)
     -> ::std::os::raw::c_int;
    pub fn fseek(arg1: *mut FILE, arg2: ::std::os::raw::c_long,
                 arg3: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
    pub fn fsetpos(arg1: *mut FILE, arg2: *const fpos_t)
     -> ::std::os::raw::c_int;
    pub fn ftell(arg1: *mut FILE) -> ::std::os::raw::c_long;
    pub fn fwrite(arg1: *const ::std::os::raw::c_void, arg2: size_t,
                  arg3: size_t, arg4: *mut FILE) -> size_t;
    pub fn getc(arg1: *mut FILE) -> ::std::os::raw::c_int;
    pub fn getchar() -> ::std::os::raw::c_int;
    pub fn gets(arg1: *mut ::std::os::raw::c_char)
     -> *mut ::std::os::raw::c_char;
    pub fn perror(arg1: *const ::std::os::raw::c_char);
    pub fn printf(arg1: *const ::std::os::raw::c_char, ...)
     -> ::std::os::raw::c_int;
    pub fn putc(arg1: ::std::os::raw::c_int, arg2: *mut FILE)
     -> ::std::os::raw::c_int;
    pub fn putchar(arg1: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
    pub fn puts(arg1: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
    pub fn remove(arg1: *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn rename(arg1: *const ::std::os::raw::c_char,
                  arg2: *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn rewind(arg1: *mut FILE);
    pub fn scanf(arg1: *const ::std::os::raw::c_char, ...)
     -> ::std::os::raw::c_int;
    pub fn setbuf(arg1: *mut FILE, arg2: *mut ::std::os::raw::c_char);
    pub fn setvbuf(arg1: *mut FILE, arg2: *mut ::std::os::raw::c_char,
                   arg3: ::std::os::raw::c_int, arg4: size_t)
     -> ::std::os::raw::c_int;
    pub fn sprintf(arg1: *mut ::std::os::raw::c_char,
                   arg2: *const ::std::os::raw::c_char, ...)
     -> ::std::os::raw::c_int;
    pub fn sscanf(arg1: *const ::std::os::raw::c_char,
                  arg2: *const ::std::os::raw::c_char, ...)
     -> ::std::os::raw::c_int;
    pub fn tmpfile() -> *mut FILE;
    pub fn tmpnam(arg1: *mut ::std::os::raw::c_char)
     -> *mut ::std::os::raw::c_char;
    pub fn ungetc(arg1: ::std::os::raw::c_int, arg2: *mut FILE)
     -> ::std::os::raw::c_int;
    pub fn vfprintf(arg1: *mut FILE, arg2: *const ::std::os::raw::c_char,
                    arg3: va_list) -> ::std::os::raw::c_int;
    pub fn vprintf(arg1: *const ::std::os::raw::c_char, arg2: va_list)
     -> ::std::os::raw::c_int;
    pub fn vsprintf(arg1: *mut ::std::os::raw::c_char,
                    arg2: *const ::std::os::raw::c_char, arg3: va_list)
     -> ::std::os::raw::c_int;
    pub fn ctermid(arg1: *mut ::std::os::raw::c_char)
     -> *mut ::std::os::raw::c_char;
    pub fn fdopen(arg1: ::std::os::raw::c_int,
                  arg2: *const ::std::os::raw::c_char) -> *mut FILE;
    pub fn fileno(arg1: *mut FILE) -> ::std::os::raw::c_int;
    pub fn pclose(arg1: *mut FILE) -> ::std::os::raw::c_int;
    pub fn popen(arg1: *const ::std::os::raw::c_char,
                 arg2: *const ::std::os::raw::c_char) -> *mut FILE;
    pub fn __srget(arg1: *mut FILE) -> ::std::os::raw::c_int;
    pub fn __svfscanf(arg1: *mut FILE, arg2: *const ::std::os::raw::c_char,
                      arg3: va_list) -> ::std::os::raw::c_int;
    pub fn __swbuf(arg1: ::std::os::raw::c_int, arg2: *mut FILE)
     -> ::std::os::raw::c_int;
    pub fn __sputc(_c: ::std::os::raw::c_int, _p: *mut FILE)
     -> ::std::os::raw::c_int;
    pub fn flockfile(arg1: *mut FILE);
    pub fn ftrylockfile(arg1: *mut FILE) -> ::std::os::raw::c_int;
    pub fn funlockfile(arg1: *mut FILE);
    pub fn getc_unlocked(arg1: *mut FILE) -> ::std::os::raw::c_int;
    pub fn getchar_unlocked() -> ::std::os::raw::c_int;
    pub fn putc_unlocked(arg1: ::std::os::raw::c_int, arg2: *mut FILE)
     -> ::std::os::raw::c_int;
    pub fn putchar_unlocked(arg1: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn getw(arg1: *mut FILE) -> ::std::os::raw::c_int;
    pub fn putw(arg1: ::std::os::raw::c_int, arg2: *mut FILE)
     -> ::std::os::raw::c_int;
    pub fn tempnam(arg1: *const ::std::os::raw::c_char,
                   arg2: *const ::std::os::raw::c_char)
     -> *mut ::std::os::raw::c_char;
    pub fn fseeko(arg1: *mut FILE, arg2: off_t, arg3: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn ftello(arg1: *mut FILE) -> off_t;
    pub fn snprintf(arg1: *mut ::std::os::raw::c_char, arg2: size_t,
                    arg3: *const ::std::os::raw::c_char, ...)
     -> ::std::os::raw::c_int;
    pub fn vfscanf(arg1: *mut FILE, arg2: *const ::std::os::raw::c_char,
                   arg3: va_list) -> ::std::os::raw::c_int;
    pub fn vscanf(arg1: *const ::std::os::raw::c_char, arg2: va_list)
     -> ::std::os::raw::c_int;
    pub fn vsnprintf(arg1: *mut ::std::os::raw::c_char, arg2: size_t,
                     arg3: *const ::std::os::raw::c_char, arg4: va_list)
     -> ::std::os::raw::c_int;
    pub fn vsscanf(arg1: *const ::std::os::raw::c_char,
                   arg2: *const ::std::os::raw::c_char, arg3: va_list)
     -> ::std::os::raw::c_int;
    pub fn dprintf(arg1: ::std::os::raw::c_int,
                   arg2: *const ::std::os::raw::c_char, ...)
     -> ::std::os::raw::c_int;
    pub fn vdprintf(arg1: ::std::os::raw::c_int,
                    arg2: *const ::std::os::raw::c_char, arg3: va_list)
     -> ::std::os::raw::c_int;
    pub fn getdelim(arg1: *mut *mut ::std::os::raw::c_char, arg2: *mut size_t,
                    arg3: ::std::os::raw::c_int, arg4: *mut FILE) -> ssize_t;
    pub fn getline(arg1: *mut *mut ::std::os::raw::c_char, arg2: *mut size_t,
                   arg3: *mut FILE) -> ssize_t;
    pub fn asprintf(arg1: *mut *mut ::std::os::raw::c_char,
                    arg2: *const ::std::os::raw::c_char, ...)
     -> ::std::os::raw::c_int;
    pub fn ctermid_r(arg1: *mut ::std::os::raw::c_char)
     -> *mut ::std::os::raw::c_char;
    pub fn fgetln(arg1: *mut FILE, arg2: *mut size_t)
     -> *mut ::std::os::raw::c_char;
    pub fn fmtcheck(arg1: *const ::std::os::raw::c_char,
                    arg2: *const ::std::os::raw::c_char)
     -> *const ::std::os::raw::c_char;
    pub fn fpurge(arg1: *mut FILE) -> ::std::os::raw::c_int;
    pub fn setbuffer(arg1: *mut FILE, arg2: *mut ::std::os::raw::c_char,
                     arg3: ::std::os::raw::c_int);
    pub fn setlinebuf(arg1: *mut FILE) -> ::std::os::raw::c_int;
    pub fn vasprintf(arg1: *mut *mut ::std::os::raw::c_char,
                     arg2: *const ::std::os::raw::c_char, arg3: va_list)
     -> ::std::os::raw::c_int;
    pub fn zopen(arg1: *const ::std::os::raw::c_char,
                 arg2: *const ::std::os::raw::c_char,
                 arg3: ::std::os::raw::c_int) -> *mut FILE;
    pub fn funopen(arg1: *const ::std::os::raw::c_void,
                   arg2:
                       ::std::option::Option<unsafe extern "C" fn(arg1:
                                                                      *mut ::std::os::raw::c_void,
                                                                  arg2:
                                                                      *mut ::std::os::raw::c_char,
                                                                  arg3:
                                                                      ::std::os::raw::c_int)
                                                 -> ::std::os::raw::c_int>,
                   arg3:
                       ::std::option::Option<unsafe extern "C" fn(arg1:
                                                                      *mut ::std::os::raw::c_void,
                                                                  arg2:
                                                                      *const ::std::os::raw::c_char,
                                                                  arg3:
                                                                      ::std::os::raw::c_int)
                                                 -> ::std::os::raw::c_int>,
                   arg4:
                       ::std::option::Option<unsafe extern "C" fn(arg1:
                                                                      *mut ::std::os::raw::c_void,
                                                                  arg2:
                                                                      fpos_t,
                                                                  arg3:
                                                                      ::std::os::raw::c_int)
                                                 -> fpos_t>,
                   arg5:
                       ::std::option::Option<unsafe extern "C" fn(arg1:
                                                                      *mut ::std::os::raw::c_void)
                                                 -> ::std::os::raw::c_int>)
     -> *mut FILE;
    pub fn __sprintf_chk(arg1: *mut ::std::os::raw::c_char,
                         arg2: ::std::os::raw::c_int, arg3: size_t,
                         arg4: *const ::std::os::raw::c_char, ...)
     -> ::std::os::raw::c_int;
    pub fn __snprintf_chk(arg1: *mut ::std::os::raw::c_char, arg2: size_t,
                          arg3: ::std::os::raw::c_int, arg4: size_t,
                          arg5: *const ::std::os::raw::c_char, ...)
     -> ::std::os::raw::c_int;
    pub fn __vsprintf_chk(arg1: *mut ::std::os::raw::c_char,
                          arg2: ::std::os::raw::c_int, arg3: size_t,
                          arg4: *const ::std::os::raw::c_char, arg5: va_list)
     -> ::std::os::raw::c_int;
    pub fn __vsnprintf_chk(arg1: *mut ::std::os::raw::c_char, arg2: size_t,
                           arg3: ::std::os::raw::c_int, arg4: size_t,
                           arg5: *const ::std::os::raw::c_char, arg6: va_list)
     -> ::std::os::raw::c_int;
    pub fn imaxabs(j: intmax_t) -> intmax_t;
    pub fn imaxdiv(__numer: intmax_t, __denom: intmax_t) -> imaxdiv_t;
    pub fn strtoimax(__nptr: *const ::std::os::raw::c_char,
                     __endptr: *mut *mut ::std::os::raw::c_char,
                     __base: ::std::os::raw::c_int) -> intmax_t;
    pub fn strtoumax(__nptr: *const ::std::os::raw::c_char,
                     __endptr: *mut *mut ::std::os::raw::c_char,
                     __base: ::std::os::raw::c_int) -> uintmax_t;
    pub fn wcstoimax(__nptr: *const wchar_t, __endptr: *mut *mut wchar_t,
                     __base: ::std::os::raw::c_int) -> intmax_t;
    pub fn wcstoumax(__nptr: *const wchar_t, __endptr: *mut *mut wchar_t,
                     __base: ::std::os::raw::c_int) -> uintmax_t;
    pub fn rd_kafka_version() -> ::std::os::raw::c_int;
    pub fn rd_kafka_version_str() -> *const ::std::os::raw::c_char;
    pub fn rd_kafka_get_debug_contexts() -> *const ::std::os::raw::c_char;
    pub fn rd_kafka_get_err_descs(errdescs: *mut *const rd_kafka_err_desc,
                                  cntp: *mut size_t);
    pub fn rd_kafka_err2str(err: rd_kafka_resp_err_t)
     -> *const ::std::os::raw::c_char;
    pub fn rd_kafka_err2name(err: rd_kafka_resp_err_t)
     -> *const ::std::os::raw::c_char;
    pub fn rd_kafka_last_error() -> rd_kafka_resp_err_t;
    pub fn rd_kafka_errno2err(errnox: ::std::os::raw::c_int)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_errno() -> ::std::os::raw::c_int;
    pub fn rd_kafka_topic_partition_destroy(rktpar:
                                                *mut rd_kafka_topic_partition_t);
    pub fn rd_kafka_topic_partition_list_new(size: ::std::os::raw::c_int)
     -> *mut rd_kafka_topic_partition_list_t;
    pub fn rd_kafka_topic_partition_list_destroy(rkparlist:
                                                     *mut rd_kafka_topic_partition_list_t);
    pub fn rd_kafka_topic_partition_list_add(rktparlist:
                                                 *mut rd_kafka_topic_partition_list_t,
                                             topic:
                                                 *const ::std::os::raw::c_char,
                                             partition: int32_t)
     -> *mut rd_kafka_topic_partition_t;
    pub fn rd_kafka_topic_partition_list_add_range(rktparlist:
                                                       *mut rd_kafka_topic_partition_list_t,
                                                   topic:
                                                       *const ::std::os::raw::c_char,
                                                   start: int32_t,
                                                   stop: int32_t);
    pub fn rd_kafka_topic_partition_list_del(rktparlist:
                                                 *mut rd_kafka_topic_partition_list_t,
                                             topic:
                                                 *const ::std::os::raw::c_char,
                                             partition: int32_t)
     -> ::std::os::raw::c_int;
    pub fn rd_kafka_topic_partition_list_del_by_idx(rktparlist:
                                                        *mut rd_kafka_topic_partition_list_t,
                                                    idx:
                                                        ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn rd_kafka_topic_partition_list_copy(src:
                                                  *const rd_kafka_topic_partition_list_t)
     -> *mut rd_kafka_topic_partition_list_t;
    pub fn rd_kafka_topic_partition_list_set_offset(rktparlist:
                                                        *mut rd_kafka_topic_partition_list_t,
                                                    topic:
                                                        *const ::std::os::raw::c_char,
                                                    partition: int32_t,
                                                    offset: int64_t)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_topic_partition_list_find(rktparlist:
                                                  *mut rd_kafka_topic_partition_list_t,
                                              topic:
                                                  *const ::std::os::raw::c_char,
                                              partition: int32_t)
     -> *mut rd_kafka_topic_partition_t;
    pub fn rd_kafka_message_destroy(rkmessage: *mut rd_kafka_message_t);
    pub fn rd_kafka_message_timestamp(rkmessage: *const rd_kafka_message_t,
                                      tstype: *mut rd_kafka_timestamp_type_t)
     -> int64_t;
    pub fn rd_kafka_conf_new() -> *mut rd_kafka_conf_t;
    pub fn rd_kafka_conf_destroy(conf: *mut rd_kafka_conf_t);
    pub fn rd_kafka_conf_dup(conf: *const rd_kafka_conf_t)
     -> *mut rd_kafka_conf_t;
    pub fn rd_kafka_conf_set(conf: *mut rd_kafka_conf_t,
                             name: *const ::std::os::raw::c_char,
                             value: *const ::std::os::raw::c_char,
                             errstr: *mut ::std::os::raw::c_char,
                             errstr_size: size_t) -> rd_kafka_conf_res_t;
    pub fn rd_kafka_conf_set_events(conf: *mut rd_kafka_conf_t,
                                    events: ::std::os::raw::c_int);
    pub fn rd_kafka_conf_set_dr_cb(conf: *mut rd_kafka_conf_t,
                                   dr_cb:
                                       ::std::option::Option<unsafe extern "C" fn(rk:
                                                                                      *mut rd_kafka_t,
                                                                                  payload:
                                                                                      *mut ::std::os::raw::c_void,
                                                                                  len:
                                                                                      size_t,
                                                                                  err:
                                                                                      rd_kafka_resp_err_t,
                                                                                  opaque:
                                                                                      *mut ::std::os::raw::c_void,
                                                                                  msg_opaque:
                                                                                      *mut ::std::os::raw::c_void)>);
    pub fn rd_kafka_conf_set_dr_msg_cb(conf: *mut rd_kafka_conf_t,
                                       dr_msg_cb:
                                           ::std::option::Option<unsafe extern "C" fn(rk:
                                                                                          *mut rd_kafka_t,
                                                                                      rkmessage:
                                                                                          *const rd_kafka_message_t,
                                                                                      opaque:
                                                                                          *mut ::std::os::raw::c_void)>);
    pub fn rd_kafka_conf_set_consume_cb(conf: *mut rd_kafka_conf_t,
                                        consume_cb:
                                            ::std::option::Option<unsafe extern "C" fn(rkmessage:
                                                                                           *mut rd_kafka_message_t,
                                                                                       opaque:
                                                                                           *mut ::std::os::raw::c_void)>);
    pub fn rd_kafka_conf_set_rebalance_cb(conf: *mut rd_kafka_conf_t,
                                          rebalance_cb:
                                              ::std::option::Option<unsafe extern "C" fn(rk:
                                                                                             *mut rd_kafka_t,
                                                                                         err:
                                                                                             rd_kafka_resp_err_t,
                                                                                         partitions:
                                                                                             *mut rd_kafka_topic_partition_list_t,
                                                                                         opaque:
                                                                                             *mut ::std::os::raw::c_void)>);
    pub fn rd_kafka_conf_set_offset_commit_cb(conf: *mut rd_kafka_conf_t,
                                              offset_commit_cb:
                                                  ::std::option::Option<unsafe extern "C" fn(rk:
                                                                                                 *mut rd_kafka_t,
                                                                                             err:
                                                                                                 rd_kafka_resp_err_t,
                                                                                             offsets:
                                                                                                 *mut rd_kafka_topic_partition_list_t,
                                                                                             opaque:
                                                                                                 *mut ::std::os::raw::c_void)>);
    pub fn rd_kafka_conf_set_error_cb(conf: *mut rd_kafka_conf_t,
                                      error_cb:
                                          ::std::option::Option<unsafe extern "C" fn(rk:
                                                                                         *mut rd_kafka_t,
                                                                                     err:
                                                                                         ::std::os::raw::c_int,
                                                                                     reason:
                                                                                         *const ::std::os::raw::c_char,
                                                                                     opaque:
                                                                                         *mut ::std::os::raw::c_void)>);
    pub fn rd_kafka_conf_set_throttle_cb(conf: *mut rd_kafka_conf_t,
                                         throttle_cb:
                                             ::std::option::Option<unsafe extern "C" fn(rk:
                                                                                            *mut rd_kafka_t,
                                                                                        broker_name:
                                                                                            *const ::std::os::raw::c_char,
                                                                                        broker_id:
                                                                                            int32_t,
                                                                                        throttle_time_ms:
                                                                                            ::std::os::raw::c_int,
                                                                                        opaque:
                                                                                            *mut ::std::os::raw::c_void)>);
    pub fn rd_kafka_conf_set_log_cb(conf: *mut rd_kafka_conf_t,
                                    log_cb:
                                        ::std::option::Option<unsafe extern "C" fn(rk:
                                                                                       *const rd_kafka_t,
                                                                                   level:
                                                                                       ::std::os::raw::c_int,
                                                                                   fac:
                                                                                       *const ::std::os::raw::c_char,
                                                                                   buf:
                                                                                       *const ::std::os::raw::c_char)>);
    pub fn rd_kafka_conf_set_stats_cb(conf: *mut rd_kafka_conf_t,
                                      stats_cb:
                                          ::std::option::Option<unsafe extern "C" fn(rk:
                                                                                         *mut rd_kafka_t,
                                                                                     json:
                                                                                         *mut ::std::os::raw::c_char,
                                                                                     json_len:
                                                                                         size_t,
                                                                                     opaque:
                                                                                         *mut ::std::os::raw::c_void)
                                                                    ->
                                                                        ::std::os::raw::c_int>);
    pub fn rd_kafka_conf_set_socket_cb(conf: *mut rd_kafka_conf_t,
                                       socket_cb:
                                           ::std::option::Option<unsafe extern "C" fn(domain:
                                                                                          ::std::os::raw::c_int,
                                                                                      type_:
                                                                                          ::std::os::raw::c_int,
                                                                                      protocol:
                                                                                          ::std::os::raw::c_int,
                                                                                      opaque:
                                                                                          *mut ::std::os::raw::c_void)
                                                                     ->
                                                                         ::std::os::raw::c_int>);
    pub fn rd_kafka_conf_set_open_cb(conf: *mut rd_kafka_conf_t,
                                     open_cb:
                                         ::std::option::Option<unsafe extern "C" fn(pathname:
                                                                                        *const ::std::os::raw::c_char,
                                                                                    flags:
                                                                                        ::std::os::raw::c_int,
                                                                                    mode:
                                                                                        mode_t,
                                                                                    opaque:
                                                                                        *mut ::std::os::raw::c_void)
                                                                   ->
                                                                       ::std::os::raw::c_int>);
    pub fn rd_kafka_conf_set_opaque(conf: *mut rd_kafka_conf_t,
                                    opaque: *mut ::std::os::raw::c_void);
    pub fn rd_kafka_opaque(rk: *const rd_kafka_t)
     -> *mut ::std::os::raw::c_void;
    pub fn rd_kafka_conf_set_default_topic_conf(conf: *mut rd_kafka_conf_t,
                                                tconf:
                                                    *mut rd_kafka_topic_conf_t);
    pub fn rd_kafka_conf_get(conf: *const rd_kafka_conf_t,
                             name: *const ::std::os::raw::c_char,
                             dest: *mut ::std::os::raw::c_char,
                             dest_size: *mut size_t) -> rd_kafka_conf_res_t;
    pub fn rd_kafka_topic_conf_get(conf: *const rd_kafka_topic_conf_t,
                                   name: *const ::std::os::raw::c_char,
                                   dest: *mut ::std::os::raw::c_char,
                                   dest_size: *mut size_t)
     -> rd_kafka_conf_res_t;
    pub fn rd_kafka_conf_dump(conf: *mut rd_kafka_conf_t, cntp: *mut size_t)
     -> *mut *const ::std::os::raw::c_char;
    pub fn rd_kafka_topic_conf_dump(conf: *mut rd_kafka_topic_conf_t,
                                    cntp: *mut size_t)
     -> *mut *const ::std::os::raw::c_char;
    pub fn rd_kafka_conf_dump_free(arr: *mut *const ::std::os::raw::c_char,
                                   cnt: size_t);
    pub fn rd_kafka_conf_properties_show(fp: *mut FILE);
    pub fn rd_kafka_topic_conf_new() -> *mut rd_kafka_topic_conf_t;
    pub fn rd_kafka_topic_conf_dup(conf: *const rd_kafka_topic_conf_t)
     -> *mut rd_kafka_topic_conf_t;
    pub fn rd_kafka_topic_conf_destroy(topic_conf:
                                           *mut rd_kafka_topic_conf_t);
    pub fn rd_kafka_topic_conf_set(conf: *mut rd_kafka_topic_conf_t,
                                   name: *const ::std::os::raw::c_char,
                                   value: *const ::std::os::raw::c_char,
                                   errstr: *mut ::std::os::raw::c_char,
                                   errstr_size: size_t)
     -> rd_kafka_conf_res_t;
    pub fn rd_kafka_topic_conf_set_opaque(conf: *mut rd_kafka_topic_conf_t,
                                          opaque:
                                              *mut ::std::os::raw::c_void);
    pub fn rd_kafka_topic_conf_set_partitioner_cb(topic_conf:
                                                      *mut rd_kafka_topic_conf_t,
                                                  partitioner:
                                                      ::std::option::Option<unsafe extern "C" fn(rkt:
                                                                                                     *const rd_kafka_topic_t,
                                                                                                 keydata:
                                                                                                     *const ::std::os::raw::c_void,
                                                                                                 keylen:
                                                                                                     size_t,
                                                                                                 partition_cnt:
                                                                                                     int32_t,
                                                                                                 rkt_opaque:
                                                                                                     *mut ::std::os::raw::c_void,
                                                                                                 msg_opaque:
                                                                                                     *mut ::std::os::raw::c_void)
                                                                                ->
                                                                                    int32_t>);
    pub fn rd_kafka_topic_partition_available(rkt: *const rd_kafka_topic_t,
                                              partition: int32_t)
     -> ::std::os::raw::c_int;
    pub fn rd_kafka_msg_partitioner_random(rkt: *const rd_kafka_topic_t,
                                           key: *const ::std::os::raw::c_void,
                                           keylen: size_t,
                                           partition_cnt: int32_t,
                                           opaque:
                                               *mut ::std::os::raw::c_void,
                                           msg_opaque:
                                               *mut ::std::os::raw::c_void)
     -> int32_t;
    pub fn rd_kafka_msg_partitioner_consistent(rkt: *const rd_kafka_topic_t,
                                               key:
                                                   *const ::std::os::raw::c_void,
                                               keylen: size_t,
                                               partition_cnt: int32_t,
                                               opaque:
                                                   *mut ::std::os::raw::c_void,
                                               msg_opaque:
                                                   *mut ::std::os::raw::c_void)
     -> int32_t;
    pub fn rd_kafka_msg_partitioner_consistent_random(rkt:
                                                          *const rd_kafka_topic_t,
                                                      key:
                                                          *const ::std::os::raw::c_void,
                                                      keylen: size_t,
                                                      partition_cnt: int32_t,
                                                      opaque:
                                                          *mut ::std::os::raw::c_void,
                                                      msg_opaque:
                                                          *mut ::std::os::raw::c_void)
     -> int32_t;
    pub fn rd_kafka_new(type_: rd_kafka_type_t, conf: *mut rd_kafka_conf_t,
                        errstr: *mut ::std::os::raw::c_char,
                        errstr_size: size_t) -> *mut rd_kafka_t;
    pub fn rd_kafka_destroy(rk: *mut rd_kafka_t);
    pub fn rd_kafka_name(rk: *const rd_kafka_t)
     -> *const ::std::os::raw::c_char;
    pub fn rd_kafka_memberid(rk: *const rd_kafka_t)
     -> *mut ::std::os::raw::c_char;
    pub fn rd_kafka_topic_new(rk: *mut rd_kafka_t,
                              topic: *const ::std::os::raw::c_char,
                              conf: *mut rd_kafka_topic_conf_t)
     -> *mut rd_kafka_topic_t;
    pub fn rd_kafka_topic_destroy(rkt: *mut rd_kafka_topic_t);
    pub fn rd_kafka_topic_name(rkt: *const rd_kafka_topic_t)
     -> *const ::std::os::raw::c_char;
    pub fn rd_kafka_topic_opaque(rkt: *const rd_kafka_topic_t)
     -> *mut ::std::os::raw::c_void;
    pub fn rd_kafka_poll(rk: *mut rd_kafka_t,
                         timeout_ms: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn rd_kafka_yield(rk: *mut rd_kafka_t);
    pub fn rd_kafka_pause_partitions(rk: *mut rd_kafka_t,
                                     partitions:
                                         *mut rd_kafka_topic_partition_list_t)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_resume_partitions(rk: *mut rd_kafka_t,
                                      partitions:
                                          *mut rd_kafka_topic_partition_list_t)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_query_watermark_offsets(rk: *mut rd_kafka_t,
                                            topic:
                                                *const ::std::os::raw::c_char,
                                            partition: int32_t,
                                            low: *mut int64_t,
                                            high: *mut int64_t,
                                            timeout_ms: ::std::os::raw::c_int)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_get_watermark_offsets(rk: *mut rd_kafka_t,
                                          topic:
                                              *const ::std::os::raw::c_char,
                                          partition: int32_t,
                                          low: *mut int64_t,
                                          high: *mut int64_t)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_mem_free(rk: *mut rd_kafka_t,
                             ptr: *mut ::std::os::raw::c_void);
    pub fn rd_kafka_queue_new(rk: *mut rd_kafka_t) -> *mut rd_kafka_queue_t;
    pub fn rd_kafka_queue_destroy(rkqu: *mut rd_kafka_queue_t);
    pub fn rd_kafka_queue_get_main(rk: *mut rd_kafka_t)
     -> *mut rd_kafka_queue_t;
    pub fn rd_kafka_queue_get_consumer(rk: *mut rd_kafka_t)
     -> *mut rd_kafka_queue_t;
    pub fn rd_kafka_queue_forward(src: *mut rd_kafka_queue_t,
                                  dst: *mut rd_kafka_queue_t);
    pub fn rd_kafka_queue_length(rkqu: *mut rd_kafka_queue_t) -> size_t;
    pub fn rd_kafka_queue_io_event_enable(rkqu: *mut rd_kafka_queue_t,
                                          fd: ::std::os::raw::c_int,
                                          payload:
                                              *const ::std::os::raw::c_void,
                                          size: size_t);
    pub fn rd_kafka_consume_start(rkt: *mut rd_kafka_topic_t,
                                  partition: int32_t, offset: int64_t)
     -> ::std::os::raw::c_int;
    pub fn rd_kafka_consume_start_queue(rkt: *mut rd_kafka_topic_t,
                                        partition: int32_t, offset: int64_t,
                                        rkqu: *mut rd_kafka_queue_t)
     -> ::std::os::raw::c_int;
    pub fn rd_kafka_consume_stop(rkt: *mut rd_kafka_topic_t,
                                 partition: int32_t) -> ::std::os::raw::c_int;
    pub fn rd_kafka_seek(rkt: *mut rd_kafka_topic_t, partition: int32_t,
                         offset: int64_t, timeout_ms: ::std::os::raw::c_int)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_consume(rkt: *mut rd_kafka_topic_t, partition: int32_t,
                            timeout_ms: ::std::os::raw::c_int)
     -> *mut rd_kafka_message_t;
    pub fn rd_kafka_consume_batch(rkt: *mut rd_kafka_topic_t,
                                  partition: int32_t,
                                  timeout_ms: ::std::os::raw::c_int,
                                  rkmessages: *mut *mut rd_kafka_message_t,
                                  rkmessages_size: size_t) -> ssize_t;
    pub fn rd_kafka_consume_callback(rkt: *mut rd_kafka_topic_t,
                                     partition: int32_t,
                                     timeout_ms: ::std::os::raw::c_int,
                                     consume_cb:
                                         ::std::option::Option<unsafe extern "C" fn(rkmessage:
                                                                                        *mut rd_kafka_message_t,
                                                                                    opaque:
                                                                                        *mut ::std::os::raw::c_void)>,
                                     opaque: *mut ::std::os::raw::c_void)
     -> ::std::os::raw::c_int;
    pub fn rd_kafka_consume_queue(rkqu: *mut rd_kafka_queue_t,
                                  timeout_ms: ::std::os::raw::c_int)
     -> *mut rd_kafka_message_t;
    pub fn rd_kafka_consume_batch_queue(rkqu: *mut rd_kafka_queue_t,
                                        timeout_ms: ::std::os::raw::c_int,
                                        rkmessages:
                                            *mut *mut rd_kafka_message_t,
                                        rkmessages_size: size_t) -> ssize_t;
    pub fn rd_kafka_consume_callback_queue(rkqu: *mut rd_kafka_queue_t,
                                           timeout_ms: ::std::os::raw::c_int,
                                           consume_cb:
                                               ::std::option::Option<unsafe extern "C" fn(rkmessage:
                                                                                              *mut rd_kafka_message_t,
                                                                                          opaque:
                                                                                              *mut ::std::os::raw::c_void)>,
                                           opaque:
                                               *mut ::std::os::raw::c_void)
     -> ::std::os::raw::c_int;
    pub fn rd_kafka_offset_store(rkt: *mut rd_kafka_topic_t,
                                 partition: int32_t, offset: int64_t)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_subscribe(rk: *mut rd_kafka_t,
                              topics: *const rd_kafka_topic_partition_list_t)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_unsubscribe(rk: *mut rd_kafka_t) -> rd_kafka_resp_err_t;
    pub fn rd_kafka_subscription(rk: *mut rd_kafka_t,
                                 topics:
                                     *mut *mut rd_kafka_topic_partition_list_t)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_consumer_poll(rk: *mut rd_kafka_t,
                                  timeout_ms: ::std::os::raw::c_int)
     -> *mut rd_kafka_message_t;
    pub fn rd_kafka_consumer_close(rk: *mut rd_kafka_t)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_assign(rk: *mut rd_kafka_t,
                           partitions: *const rd_kafka_topic_partition_list_t)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_assignment(rk: *mut rd_kafka_t,
                               partitions:
                                   *mut *mut rd_kafka_topic_partition_list_t)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_commit(rk: *mut rd_kafka_t,
                           offsets: *const rd_kafka_topic_partition_list_t,
                           async: ::std::os::raw::c_int)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_commit_message(rk: *mut rd_kafka_t,
                                   rkmessage: *const rd_kafka_message_t,
                                   async: ::std::os::raw::c_int)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_commit_queue(rk: *mut rd_kafka_t,
                                 offsets:
                                     *const rd_kafka_topic_partition_list_t,
                                 rkqu: *mut rd_kafka_queue_t,
                                 cb:
                                     ::std::option::Option<unsafe extern "C" fn(rk:
                                                                                    *mut rd_kafka_t,
                                                                                err:
                                                                                    rd_kafka_resp_err_t,
                                                                                offsets:
                                                                                    *mut rd_kafka_topic_partition_list_t,
                                                                                opaque:
                                                                                    *mut ::std::os::raw::c_void)>,
                                 opaque: *mut ::std::os::raw::c_void)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_committed(rk: *mut rd_kafka_t,
                              partitions:
                                  *mut rd_kafka_topic_partition_list_t,
                              timeout_ms: ::std::os::raw::c_int)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_position(rk: *mut rd_kafka_t,
                             partitions: *mut rd_kafka_topic_partition_list_t)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_produce(rkt: *mut rd_kafka_topic_t, partition: int32_t,
                            msgflags: ::std::os::raw::c_int,
                            payload: *mut ::std::os::raw::c_void, len: size_t,
                            key: *const ::std::os::raw::c_void,
                            keylen: size_t,
                            msg_opaque: *mut ::std::os::raw::c_void)
     -> ::std::os::raw::c_int;
    pub fn rd_kafka_produce_batch(rkt: *mut rd_kafka_topic_t,
                                  partition: int32_t,
                                  msgflags: ::std::os::raw::c_int,
                                  rkmessages: *mut rd_kafka_message_t,
                                  message_cnt: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn rd_kafka_flush(rk: *mut rd_kafka_t,
                          timeout_ms: ::std::os::raw::c_int)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_metadata(rk: *mut rd_kafka_t,
                             all_topics: ::std::os::raw::c_int,
                             only_rkt: *mut rd_kafka_topic_t,
                             metadatap: *mut *const rd_kafka_metadata,
                             timeout_ms: ::std::os::raw::c_int)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_metadata_destroy(metadata: *const rd_kafka_metadata);
    pub fn rd_kafka_list_groups(rk: *mut rd_kafka_t,
                                group: *const ::std::os::raw::c_char,
                                grplistp: *mut *const rd_kafka_group_list,
                                timeout_ms: ::std::os::raw::c_int)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_group_list_destroy(grplist: *const rd_kafka_group_list);
    pub fn rd_kafka_brokers_add(rk: *mut rd_kafka_t,
                                brokerlist: *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn rd_kafka_set_logger(rk: *mut rd_kafka_t,
                               func:
                                   ::std::option::Option<unsafe extern "C" fn(rk:
                                                                                  *const rd_kafka_t,
                                                                              level:
                                                                                  ::std::os::raw::c_int,
                                                                              fac:
                                                                                  *const ::std::os::raw::c_char,
                                                                              buf:
                                                                                  *const ::std::os::raw::c_char)>);
    pub fn rd_kafka_set_log_level(rk: *mut rd_kafka_t,
                                  level: ::std::os::raw::c_int);
    pub fn rd_kafka_log_print(rk: *const rd_kafka_t,
                              level: ::std::os::raw::c_int,
                              fac: *const ::std::os::raw::c_char,
                              buf: *const ::std::os::raw::c_char);
    pub fn rd_kafka_log_syslog(rk: *const rd_kafka_t,
                               level: ::std::os::raw::c_int,
                               fac: *const ::std::os::raw::c_char,
                               buf: *const ::std::os::raw::c_char);
    pub fn rd_kafka_outq_len(rk: *mut rd_kafka_t) -> ::std::os::raw::c_int;
    pub fn rd_kafka_dump(fp: *mut FILE, rk: *mut rd_kafka_t);
    pub fn rd_kafka_thread_cnt() -> ::std::os::raw::c_int;
    pub fn rd_kafka_wait_destroyed(timeout_ms: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn rd_kafka_poll_set_consumer(rk: *mut rd_kafka_t)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_event_type(rkev: *const rd_kafka_event_t)
     -> rd_kafka_event_type_t;
    pub fn rd_kafka_event_name(rkev: *const rd_kafka_event_t)
     -> *const ::std::os::raw::c_char;
    pub fn rd_kafka_event_destroy(rkev: *mut rd_kafka_event_t);
    pub fn rd_kafka_event_message_next(rkev: *mut rd_kafka_event_t)
     -> *const rd_kafka_message_t;
    pub fn rd_kafka_event_message_array(rkev: *mut rd_kafka_event_t,
                                        rkmessages:
                                            *mut *const rd_kafka_message_t,
                                        size: size_t) -> size_t;
    pub fn rd_kafka_event_message_count(rkev: *mut rd_kafka_event_t)
     -> size_t;
    pub fn rd_kafka_event_error(rkev: *mut rd_kafka_event_t)
     -> rd_kafka_resp_err_t;
    pub fn rd_kafka_event_error_string(rkev: *mut rd_kafka_event_t)
     -> *const ::std::os::raw::c_char;
    pub fn rd_kafka_event_opaque(rkev: *mut rd_kafka_event_t)
     -> *mut ::std::os::raw::c_void;
    pub fn rd_kafka_event_log(rkev: *mut rd_kafka_event_t,
                              fac: *mut *const ::std::os::raw::c_char,
                              str: *mut *const ::std::os::raw::c_char,
                              level: *mut ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn rd_kafka_event_topic_partition_list(rkev: *mut rd_kafka_event_t)
     -> *mut rd_kafka_topic_partition_list_t;
    pub fn rd_kafka_event_topic_partition(rkev: *mut rd_kafka_event_t)
     -> *mut rd_kafka_topic_partition_t;
    pub fn rd_kafka_queue_poll(rkqu: *mut rd_kafka_queue_t,
                               timeout_ms: ::std::os::raw::c_int)
     -> *mut rd_kafka_event_t;
}
